name: computo
channels:
    - default
dependencies:
    - python
    - pip
    - pip:
        - jupytext
        - matplotlib
        - numpy
        - nbconvert
        - ipykernel
        - jupyter-book
